### ISSUE TITLE
like your boilerplate, some news in next time?

### ISSUE THREAD

**Issue by Chriscxa** [icebob/vue-express-mongo-boilerplate#26]

**Comment by Chriscxa** [comment]
Server-Side-Rendering works? = SEO!
Security? 
Hope this project is not death and more comming soon.

**Comment by icebob** [comment]
The project is live. But I have not enough free time and I'm develop alone, so I can do it slowly. 
Currently I'm working on a microservices framework too what I will want to integrate to boilerplate. Otherwise, I have also a huge [TODO](https://github.com/icebob/vue-express-mongo-boilerplate/issues/11) list.
> I added SSR to TODO list.

**Comment by Chriscxa** [comment]
hmm... your demoSite is down

**Comment by icebob** [comment]
It's working for me.

**Comment by Chriscxa** [comment]
nop. 
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server
